"""Stable public imports for character and campaign generation."""

from dungeon_master.generation.character import (
    CHARACTER_QUIZ_SYSTEM_PROMPT,
    CHARACTER_QUIZ_USER_PROMPT_TEMPLATE,
    CHARACTER_SYSTEM_PROMPT,
    CHARACTER_TEMPLATES_USER_PROMPT,
    DRAFT_FROM_QUIZ_PROMPT,
    DRAFT_SCRATCH_PROMPT,
    DRAFT_TEMPLATE_PROMPT,
    CharacterGenerator,
)
from dungeon_master.generation.contracts import (
    GENERATION_ERRORS,
    CampaignGenerationError,
    CampaignWorldResult,
    CharacterDraftMode,
    CharacterDraftResult,
    CharacterGenerationError,
    CharacterQuizResult,
    CharacterTemplatesResult,
    GeneratedCampaignWorld,
    GeneratedCharacter,
    GeneratedCharacterQuiz,
    GeneratedCharacterTemplates,
    GeneratedInventoryItem,
    GeneratedNPC,
    GeneratedQuizOption,
    GeneratedQuizQuestion,
    GeneratedThread,
)
from dungeon_master.generation.direction import (
    GENRE_LABELS,
    render_creative_direction,
    render_danger_guidance,
)
from dungeon_master.generation.world import (
    CAMPAIGN_SYSTEM_PROMPT,
    CAMPAIGN_USER_PROMPT_TEMPLATE,
    CampaignGenerator,
)

__all__ = [
    "CAMPAIGN_SYSTEM_PROMPT",
    "CAMPAIGN_USER_PROMPT_TEMPLATE",
    "CHARACTER_QUIZ_SYSTEM_PROMPT",
    "CHARACTER_QUIZ_USER_PROMPT_TEMPLATE",
    "CHARACTER_SYSTEM_PROMPT",
    "CHARACTER_TEMPLATES_USER_PROMPT",
    "DRAFT_FROM_QUIZ_PROMPT",
    "DRAFT_SCRATCH_PROMPT",
    "DRAFT_TEMPLATE_PROMPT",
    "GENERATION_ERRORS",
    "GENRE_LABELS",
    "CampaignGenerationError",
    "CampaignGenerator",
    "CampaignWorldResult",
    "CharacterDraftMode",
    "CharacterDraftResult",
    "CharacterGenerationError",
    "CharacterGenerator",
    "CharacterQuizResult",
    "CharacterTemplatesResult",
    "GeneratedCampaignWorld",
    "GeneratedCharacter",
    "GeneratedCharacterQuiz",
    "GeneratedCharacterTemplates",
    "GeneratedInventoryItem",
    "GeneratedNPC",
    "GeneratedQuizOption",
    "GeneratedQuizQuestion",
    "GeneratedThread",
    "render_creative_direction",
    "render_danger_guidance",
]
